Dosyamı __init__ fonksiyonunda 'a+' modunda açıp oluşturmayı başardım ama diğer fonksiyonlarda 'self.file' ifadesi ile açamadım. Farklı modlarda açmaya çalıştığım için hatalar aldım durdum.
Bu sorunu çözemediğim için fonksionlarda dosya açmak için 'file = open("dosya_uzantısı", 'r+')' şeklinde yazmaktan başka çözüm bulamadım.

Bunun haricinde kendimi ifade etmem gerektiğini hissettiğim bir yer yok. 
Projeyi açıklandığı zaman yapılması gerekenler netti ama yazmaya başlayınca işin rengi değişti. Sonunda başardığımı düşünüyorum. Teşekkürler.
